import { z } from 'zod'

import { createApiResponseSchema, createApiSuccessSchema } from './api'

/** Pipeline phase values are the wire-level names accepted by the manual canvas workstation. */
export const PipelinePhaseSchema = z.enum([
  'analyze',
  'characters',
  'locations',
  'characterRefs',
  'locationRefs',
  'storyboard',
  'continuity',
  'rebuild',
  'dialogue',
  'videos',
  'bgm',
  'assemble',
])

export type PipelinePhase = z.infer<typeof PipelinePhaseSchema>

/** Pipeline project status values mirror the database enum exposed through the API. */
export const PipelineProjectStatusSchema = z.enum([
  'draft',
  'analyzed',
  'characters_ready',
  'locations_ready',
  'refs_ready',
  'refs_all_ready',
  'storyboard_ready',
  'continuity_checked',
  'prompts_ready',
  'generating',
  'completed',
  'partial_failed',
  'failed',
])

export type PipelineProjectStatus = z.infer<typeof PipelineProjectStatusSchema>

/** Pipeline run status values are the durable task lifecycle states shown in run history. */
export const PipelineRunStatusSchema = z.enum(['pending', 'running', 'succeeded', 'failed', 'cancelled'])

export type PipelineRunStatus = z.infer<typeof PipelineRunStatusSchema>

/** Shot status values describe generation progress for a single storyboard shot. */
export const PipelineShotStatusSchema = z.enum(['draft', 'ready', 'generating', 'completed', 'failed'])

export type PipelineShotStatus = z.infer<typeof PipelineShotStatusSchema>

/** Location type values come from the scene profile generated by the pipeline. */
export const PipelineLocationTypeSchema = z.enum(['interior', 'exterior', 'mixed'])

export type PipelineLocationType = z.infer<typeof PipelineLocationTypeSchema>

/**
 * Generic JSON object boundary for nested LLM/provider payloads that are persisted
 * as JSONB and refined by domain-specific code after the HTTP contract boundary.
 */
export const PipelineJsonObjectSchema = z.record(z.string(), z.unknown())

export type PipelineJsonObject = z.infer<typeof PipelineJsonObjectSchema>

/** A compact project item used by pipeline list, create, and update endpoints. */
export const PipelineProjectSummarySchema = z.object({
  id: z.string(),
  accountId: z.string(),
  title: z.string().nullable(),
  storyText: z.string(),
  status: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export type PipelineProjectSummary = z.infer<typeof PipelineProjectSummarySchema>

/** Paginated project list payload returned by GET /api/pipeline/projects. */
export const PipelineProjectListDataSchema = z.object({
  items: z.array(PipelineProjectSummarySchema),
  total: z.number().int().nonnegative(),
})

export type PipelineProjectListData = z.infer<typeof PipelineProjectListDataSchema>

/** Character resource returned by project detail and character update endpoints. */
export const PipelineCharacterDtoSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  role: z.string().nullable(),
  description: z.string().nullable(),
  profile: PipelineJsonObjectSchema.nullable(),
  identityPrompt: z.string().nullable(),
  negativePrompt: z.string().nullable(),
  referenceImageUrl: z.string().nullable(),
  turnaroundSheetUrl: z.string().nullable(),
  locked: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export type PipelineCharacterDto = z.infer<typeof PipelineCharacterDtoSchema>

/** Location resource returned by project detail and location update endpoints. */
export const PipelineLocationDtoSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  type: PipelineLocationTypeSchema,
  profile: PipelineJsonObjectSchema.nullable(),
  scenePrompt: z.string().nullable(),
  negativePrompt: z.string().nullable(),
  referenceImageUrl: z.string().nullable(),
  locked: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export type PipelineLocationDto = z.infer<typeof PipelineLocationDtoSchema>

/** Shot resource returned by project detail and shot update endpoints. */
export const PipelineShotDtoSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  shotIndex: z.number().int(),
  duration: z.number().int(),
  locationId: z.string().nullable(),
  characterIds: z.array(z.string()),
  narrative: z.string(),
  camera: PipelineJsonObjectSchema,
  continuity: PipelineJsonObjectSchema,
  timeline: z.array(PipelineJsonObjectSchema).nullable(),
  environment: PipelineJsonObjectSchema.nullable(),
  videoPrompt: z.string().nullable(),
  negativePrompt: z.string().nullable(),
  videoTaskId: z.string().nullable(),
  videoUrl: z.string().nullable(),
  status: PipelineShotStatusSchema,
  errorMessage: z.string().nullable(),
  referenceAssets: z.array(PipelineJsonObjectSchema),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export type PipelineShotDto = z.infer<typeof PipelineShotDtoSchema>

/** Full project detail payload returned by GET /api/pipeline/projects/:id. */
export const PipelineProjectDtoSchema = z.object({
  id: z.string(),
  accountId: z.string(),
  title: z.string().nullable(),
  storyText: z.string(),
  status: PipelineProjectStatusSchema,
  analysis: PipelineJsonObjectSchema.nullable(),
  modelPreferences: PipelineJsonObjectSchema.nullable(),
  characters: z.array(PipelineCharacterDtoSchema),
  locations: z.array(PipelineLocationDtoSchema),
  shots: z.array(PipelineShotDtoSchema),
  continuityIssues: z.array(PipelineJsonObjectSchema),
  canvasLayout: PipelineJsonObjectSchema.nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export type PipelineProjectDto = z.infer<typeof PipelineProjectDtoSchema>

/** Task trigger payload returned by the 12 manual phase endpoints and retry. */
export const PipelineTriggerPhaseDataSchema = z.object({
  runId: z.string(),
  taskId: z.string(),
  taskType: z.string(),
  phase: PipelinePhaseSchema,
})

export type PipelineTriggerPhaseData = z.infer<typeof PipelineTriggerPhaseDataSchema>

/** Cancel payload returned by POST /api/pipeline/projects/:id/cancel. */
export const PipelineCancelDataSchema = z.object({
  cancelled: z.number().int().nonnegative(),
})

export type PipelineCancelData = z.infer<typeof PipelineCancelDataSchema>

/** Run history item returned by GET /api/pipeline/projects/:id/runs. */
export const PipelineRunDtoSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  phase: PipelinePhaseSchema,
  status: PipelineRunStatusSchema,
  startedAt: z.string().nullable(),
  finishedAt: z.string().nullable(),
  errorMessage: z.string().nullable(),
  createdBy: z.string().nullable(),
  inputSnapshotJson: PipelineJsonObjectSchema.nullable(),
  outputSummaryJson: PipelineJsonObjectSchema.nullable(),
  taskId: z.string().nullable(),
  createdAt: z.string(),
})

export type PipelineRunDto = z.infer<typeof PipelineRunDtoSchema>

export const PipelineProjectListSuccessSchema = createApiSuccessSchema(PipelineProjectListDataSchema)
export const PipelineProjectListResponseSchema = createApiResponseSchema(PipelineProjectListDataSchema)
export const PipelineProjectSuccessSchema = createApiSuccessSchema(PipelineProjectDtoSchema)
export const PipelineProjectResponseSchema = createApiResponseSchema(PipelineProjectDtoSchema)
export const PipelineProjectSummarySuccessSchema = createApiSuccessSchema(PipelineProjectSummarySchema)
export const PipelineProjectSummaryResponseSchema = createApiResponseSchema(PipelineProjectSummarySchema)
export const PipelineTriggerPhaseSuccessSchema = createApiSuccessSchema(PipelineTriggerPhaseDataSchema)
export const PipelineTriggerPhaseResponseSchema = createApiResponseSchema(PipelineTriggerPhaseDataSchema)
export const PipelineCancelSuccessSchema = createApiSuccessSchema(PipelineCancelDataSchema)
export const PipelineCancelResponseSchema = createApiResponseSchema(PipelineCancelDataSchema)
export const PipelineRunListSuccessSchema = createApiSuccessSchema(z.array(PipelineRunDtoSchema))
export const PipelineRunListResponseSchema = createApiResponseSchema(z.array(PipelineRunDtoSchema))
